# O3DE Pilot CLI - Gem Commands
# SPDX-License-Identifier: Apache-2.0 OR MIT

"""Gem management commands."""

import click
from pathlib import Path
from rich.console import Console
from rich.table import Table

console = Console()


@click.group()
def gem() -> None:
    """Manage O3DE gems."""
    pass


@gem.command("list")
@click.option("--json", "as_json", is_flag=True, help="Output as JSON")
def list_gems(as_json: bool) -> None:
    """List all registered gems."""
    from o3de_pilot.core.resolver import Resolver
    
    resolver = Resolver()
    resolver.resolve()
    gems = resolver.gems
    
    if as_json:
        import json
        items = []
        for name, obj in gems.items():
            items.append({"name": obj.name, "version": obj.version, "path": str(obj.path)})
        click.echo(json.dumps(items, indent=2))
        return
    
    if not gems:
        console.print("[yellow]No gems registered.[/yellow]")
        console.print("Use [bold]o3de-pilot install <gem>[/bold] to install gems.")
        return
    
    table = Table(title="Registered Gems")
    table.add_column("Name", style="cyan")
    table.add_column("Version", style="green")
    table.add_column("Path", style="dim")
    
    for name, obj in gems.items():
        table.add_row(obj.name, obj.version or "unknown", str(obj.path))
    
    console.print(table)


@gem.command("create")
@click.argument("name")
@click.option("--path", "-p", type=click.Path(), help="Gem path")
@click.option("--template", "-t", "template_name", help="Gem template to use")
def create(name: str, path: str | None, template_name: str | None) -> None:
    """Create a new gem from a template."""
    import json
    from o3de_pilot.core.paths import get_manifest_path
    from o3de_pilot.core.resolver import Resolver
    
    gem_path = Path(path) if path else Path.cwd() / name
    
    console.print(f"[bold]Creating gem:[/bold] {name}")
    
    if gem_path.exists():
        console.print(f"[red]Path already exists:[/red] {gem_path}")
        raise SystemExit(1)
    
    # If a template is specified, find it in resolved objects
    template_data = None
    if template_name:
        try:
            resolver = Resolver()
            resolver.resolve()
            for tpl_name, tpl_obj in resolver.templates.items():
                if template_name in tpl_name or template_name == tpl_name:
                    template_data = tpl_obj
                    break
        except Exception:
            pass
    
    # Create gem directory structure
    gem_path.mkdir(parents=True)
    (gem_path / "Code").mkdir()
    (gem_path / "Code" / "Source").mkdir()
    
    # If template found, copy its structure
    if template_data and template_data.path.exists():
        import shutil
        # Copy template contents, skipping template metadata
        for item in template_data.path.iterdir():
            if item.name.startswith("template"):
                continue  # Skip template.json
            dest = gem_path / item.name
            if item.is_dir():
                shutil.copytree(item, dest, dirs_exist_ok=True)
            else:
                shutil.copy2(item, dest)
        console.print(f"[dim]Applied template: {template_name}[/dim]")
    
    # Create gem.2-0-0.json
    gem_json = {
        "$schema": "https://overlo3de.com/o3de-gem-2.0.0.json",
        "$schemaVersion": "2.0.0",
        "gem": {
            "name": name,
            "display_name": name.split(".")[-1],
            "version": "1.0.0",
            "description": f"A new O3DE gem: {name}",
        }
    }
    with open(gem_path / "gem.2-0-0.json", "w") as f:
        json.dump(gem_json, f, indent=2)
    
    # Create CMakeLists.txt
    short_name = name.split(".")[-1]
    cmake_content = f"""# Auto-generated by o3de-pilot
ly_add_target(
    NAME {short_name} ${{PAL_TRAIT_MONOLITHIC}}
    NAMESPACE Gem
    FILES_CMAKE
        {short_name.lower()}_files.cmake
    INCLUDE_DIRECTORIES
        PUBLIC
            Include
    BUILD_DEPENDENCIES
        PRIVATE
            AZ::AzCore
)
"""
    with open(gem_path / "CMakeLists.txt", "w") as f:
        f.write(cmake_content)
    
    console.print(f"[green]Created gem:[/green] {gem_path}")
    console.print("[dim]Add it to your manifest with: o3de-pilot manifest add <path>[/dim]")


@gem.command("info")
@click.argument("name")
def info(name: str) -> None:
    """Show information about a gem."""
    from o3de_pilot.core.resolver import Resolver, load_resolved_manifest
    
    try:
        resolved = load_resolved_manifest()
    except Exception:
        console.print("[yellow]No resolved manifest. Run 'manifest resolve' first.[/yellow]")
        raise SystemExit(1)
    
    # Search in resolved objects
    obj_data = None
    for obj_name, obj_info in resolved.get("objects", {}).items():
        if obj_info.get("type") == "gem" and (name in obj_name or name == obj_name):
            obj_data = obj_info
            obj_data["_name"] = obj_name
            break
    
    if not obj_data:
        console.print(f"[red]Gem not found:[/red] {name}")
        console.print("[dim]Use 'gem list' to see registered gems.[/dim]")
        raise SystemExit(1)
    
    console.print(f"\n[bold cyan]{obj_data['_name']}[/bold cyan]")
    console.print(f"  Version:  {obj_data.get('version', 'unknown')}")
    console.print(f"  Path:     {obj_data.get('path', 'unknown')}")
    console.print(f"  Type:     {obj_data.get('type', 'unknown')}")
    
    meta = obj_data.get("display_metadata") or {}
    if meta.get("display_name"):
        console.print(f"  Display:  {meta['display_name']}")
    if meta.get("summary"):
        console.print(f"  Summary:  {meta['summary']}")
    
    deps = obj_data.get("dependencies", [])
    if deps:
        console.print(f"  Deps:     {', '.join(deps)}")
    
    dependents = obj_data.get("dependents", [])
    if dependents:
        console.print(f"  Used by:  {', '.join(dependents)}")
    
    git = obj_data.get("git_info") or {}
    if git.get("remote_url"):
        console.print(f"  Git:      {git['remote_url']}")
    
    releases = obj_data.get("releases") or []
    if releases:
        console.print(f"  Releases: {', '.join(releases[:5])}")
    
    console.print()


@gem.command("search")
@click.argument("query")
@click.option("--json", "as_json", is_flag=True, help="Output as JSON")
def search(query: str, as_json: bool) -> None:
    """Search for gems in local manifest and remote registries."""
    import json as json_module
    from o3de_pilot.core.store import Store
    
    store = Store()
    results = store.search(query)
    
    # Filter to gems only
    gem_results = [r for r in results if r.object_type.value == "gem"]
    
    if not gem_results:
        console.print(f"[yellow]No gems found matching:[/yellow] {query}")
        return
    
    if as_json:
        output = [{"name": r.name, "version": r.version, "summary": r.summary} for r in gem_results]
        click.echo(json_module.dumps(output, indent=2))
        return
    
    table = Table(title=f"Gems matching '{query}'")
    table.add_column("Name", style="cyan")
    table.add_column("Version", style="green")
    table.add_column("Summary", style="dim")
    
    for r in gem_results:
        table.add_row(r.name, r.version, r.summary or "")
    
    console.print(table)


@gem.command("register")
@click.argument("path_or_url")
@click.option("--remote", is_flag=True, help="Register a remote URL instead of a local path")
def register_gem(path_or_url: str, remote: bool) -> None:
    """Register a gem by adding its path to the manifest."""
    import json
    from o3de_pilot.core.paths import get_manifest_path

    manifest_path = get_manifest_path()
    if not manifest_path.exists():
        console.print("[red]No manifest found.[/red]")
        raise SystemExit(1)

    with open(manifest_path) as f:
        manifest = json.load(f)

    if remote:
        console.print(f"[bold]Registering remote gem:[/bold] {path_or_url}")
        section = manifest.setdefault("remote", {})
        gems_list = section.setdefault("gems", [])
        if path_or_url in gems_list:
            console.print("[yellow]Remote gem already registered.[/yellow]")
            return
        gems_list.append(path_or_url)
    else:
        gem_path = Path(path_or_url).resolve()
        console.print(f"[bold]Registering gem:[/bold] {gem_path}")
        is_gem = any((gem_path / f).exists() for f in ["gem.2-0-0.json", "gem.json"])
        if not is_gem:
            console.print("[red]No gem JSON found at this path.[/red]")
            raise SystemExit(1)
        section = manifest.setdefault("local", {})
        gems_list = section.setdefault("gems", [])
        path_str = gem_path.as_posix()
        if path_str in gems_list:
            console.print("[yellow]Gem already registered.[/yellow]")
            return
        gems_list.append(path_str)

    with open(manifest_path, "w") as f:
        json.dump(manifest, f, indent=2)

    console.print(f"[green]Registered gem:[/green] {path_or_url}")


@gem.command("unregister")
@click.argument("name")
@click.option("--remote", is_flag=True, help="Remove from remote section instead of local")
def unregister_gem(name: str, remote: bool) -> None:
    """Unregister a gem by removing it from the manifest."""
    import json
    from o3de_pilot.core.paths import get_manifest_path

    manifest_path = get_manifest_path()
    if not manifest_path.exists():
        console.print("[red]No manifest found.[/red]")
        raise SystemExit(1)

    with open(manifest_path) as f:
        manifest = json.load(f)

    section_key = "remote" if remote else "local"
    label = "remote gem" if remote else "gem"
    console.print(f"[bold]Unregistering {label}:[/bold] {name}")

    section = manifest.get(section_key, {})
    gems_list = section.get("gems", [])

    original_len = len(gems_list)
    gems_list = [g for g in gems_list if name not in g]

    if len(gems_list) == original_len:
        console.print(f"[yellow]Gem '{name}' not found in {section_key} manifest.[/yellow]")
        return

    section["gems"] = gems_list
    manifest[section_key] = section

    with open(manifest_path, "w") as f:
        json.dump(manifest, f, indent=2)

    console.print(f"[green]Unregistered gem:[/green] {name}")
