# O3DE Pilot CLI - Project Commands
# SPDX-License-Identifier: Apache-2.0 OR MIT

"""Project management commands."""

import click
from pathlib import Path
from rich.console import Console
from rich.table import Table

console = Console()


@click.group()
def project() -> None:
    """Manage O3DE projects."""
    pass


@project.command("list")
@click.option("--json", "as_json", is_flag=True, help="Output as JSON")
def list_projects(as_json: bool) -> None:
    """List all registered projects."""
    from o3de_pilot.core.resolver import Resolver
    
    resolver = Resolver()
    resolver.resolve()
    projects = resolver.projects
    
    if as_json:
        import json
        items = []
        for name, obj in projects.items():
            items.append({
                "name": obj.name,
                "path": str(obj.path),
                "engine": obj.data.get("engine") or obj.data.get("engine_name"),
                "version": obj.version,
            })
        click.echo(json.dumps(items, indent=2))
        return
    
    if not projects:
        console.print("[yellow]No projects registered.[/yellow]")
        console.print("Use [bold]o3de-pilot init <name>[/bold] to create a new project.")
        return
    
    table = Table(title="Registered Projects")
    table.add_column("Name", style="cyan")
    table.add_column("Path", style="dim")
    table.add_column("Engine", style="green")
    
    for name, obj in projects.items():
        engine = obj.data.get("engine") or obj.data.get("engine_name") or "default"
        table.add_row(obj.name, str(obj.path), engine)
    
    console.print(table)


@project.command("init")
@click.argument("name")
@click.option("--path", "-p", type=click.Path(), help="Project path")
@click.option("--template", "-t", "template_name", help="Template to use")
def init_command(name: str, path: str | None, template_name: str | None) -> None:
    """Create a new O3DE project."""
    init_project(name, path, template_name)


def init_project(name: str, path: str | None, template_name: str | None) -> None:
    """Initialize a new O3DE project."""
    import json
    
    project_path = Path(path) if path else Path.cwd() / name
    
    console.print(f"[bold]Creating project:[/bold] {name}")
    
    if project_path.exists():
        console.print(f"[red]Path already exists:[/red] {project_path}")
        raise SystemExit(1)
    
    # If a template is specified, try to apply it
    template_data = None
    if template_name:
        try:
            from o3de_pilot.core.resolver import Resolver
            resolver = Resolver()
            resolver.resolve()
            for tpl_name, tpl_obj in resolver.templates.items():
                if template_name in tpl_name or template_name == tpl_name:
                    template_data = tpl_obj
                    break
        except Exception:
            pass
    
    # Create project directory
    project_path.mkdir(parents=True)
    (project_path / "Code").mkdir()
    (project_path / "Gems").mkdir()
    (project_path / "Assets").mkdir()
    
    if template_data and template_data.path.exists():
        import shutil
        for item in template_data.path.iterdir():
            if item.name.startswith("template"):
                continue
            dest = project_path / item.name
            if item.is_dir():
                shutil.copytree(item, dest, dirs_exist_ok=True)
            else:
                shutil.copy2(item, dest)
        console.print(f"[dim]Applied template: {template_name}[/dim]")
    
    # Create project.2-0-0.json
    project_json = {
        "$schema": "https://overlo3de.com/o3de-project-2.0.0.json",
        "$schemaVersion": "2.0.0",
        "project": {
            "name": name,
            "display_name": name.split(".")[-1],
            "version": "1.0.0",
            "description": f"A new O3DE project: {name}",
        }
    }
    with open(project_path / "project.2-0-0.json", "w") as f:
        json.dump(project_json, f, indent=2)
    
    # Create CMakeLists.txt
    short_name = name.split(".")[-1]
    cmake_content = f"""# Auto-generated by o3de-pilot
cmake_minimum_required(VERSION 3.22)
project({short_name} LANGUAGES CXX)
find_package(o3de REQUIRED)
o3de_pal_dir(pal_dir ${{CMAKE_CURRENT_LIST_DIR}}/cmake ${{O3DE_ENGINE_RESTRICTED_PATH}} ${{gem_restricted_path}} ${{gem_name}} ${{gem_path}})
"""
    with open(project_path / "CMakeLists.txt", "w") as f:
        f.write(cmake_content)
    
    console.print(f"[green]Created project:[/green] {project_path}")
    console.print("[dim]Add it to your manifest with: o3de-pilot manifest add <path>[/dim]")


@project.command("register")
@click.argument("path_or_url")
@click.option("--remote", is_flag=True, help="Register a remote URL instead of a local path")
def register_project(path_or_url: str, remote: bool) -> None:
    """Register a project by adding its path to the manifest."""
    import json
    from o3de_pilot.core.paths import get_manifest_path

    manifest_path = get_manifest_path()
    if not manifest_path.exists():
        console.print("[red]No manifest found.[/red]")
        raise SystemExit(1)

    with open(manifest_path) as f:
        manifest = json.load(f)

    if remote:
        console.print(f"[bold]Registering remote project:[/bold] {path_or_url}")
        section = manifest.setdefault("remote", {})
        projects_list = section.setdefault("projects", [])
        if path_or_url in projects_list:
            console.print("[yellow]Remote project already registered.[/yellow]")
            return
        projects_list.append(path_or_url)
    else:
        project_path = Path(path_or_url).resolve()
        console.print(f"[bold]Registering project:[/bold] {project_path}")
        is_project = any((project_path / f).exists() for f in ["project.2-0-0.json", "project.json"])
        if not is_project:
            console.print("[red]No project JSON found at this path.[/red]")
            raise SystemExit(1)
        section = manifest.setdefault("local", {})
        projects_list = section.setdefault("projects", [])
        path_str = project_path.as_posix()
        if path_str in projects_list:
            console.print("[yellow]Project already registered.[/yellow]")
            return
        projects_list.append(path_str)

    with open(manifest_path, "w") as f:
        json.dump(manifest, f, indent=2)

    console.print(f"[green]Registered project:[/green] {path_or_url}")


@project.command("unregister")
@click.argument("name")
@click.option("--remote", is_flag=True, help="Remove from remote section instead of local")
def unregister_project(name: str, remote: bool) -> None:
    """Unregister a project by removing it from the manifest."""
    import json
    from o3de_pilot.core.paths import get_manifest_path

    manifest_path = get_manifest_path()
    if not manifest_path.exists():
        console.print("[red]No manifest found.[/red]")
        raise SystemExit(1)

    with open(manifest_path) as f:
        manifest = json.load(f)

    section_key = "remote" if remote else "local"
    label = "remote project" if remote else "project"
    console.print(f"[bold]Unregistering {label}:[/bold] {name}")

    section = manifest.get(section_key, {})
    projects_list = section.get("projects", [])

    original_len = len(projects_list)
    projects_list = [p for p in projects_list if name not in p]

    if len(projects_list) == original_len:
        console.print(f"[yellow]Project '{name}' not found in {section_key} manifest.[/yellow]")
        return

    section["projects"] = projects_list
    manifest[section_key] = section

    with open(manifest_path, "w") as f:
        json.dump(manifest, f, indent=2)

    console.print(f"[green]Unregistered {label}:[/green] {name}")


@project.command("build")
@click.option("--path", "-p", type=click.Path(exists=True), help="Project path")
@click.option("--config", "-c", type=click.Choice(["debug", "profile", "release"]), default="profile")
def build(path: str | None, config: str) -> None:
    """Build an O3DE project using CMake."""
    import subprocess
    
    project_path = Path(path) if path else Path.cwd()
    build_dir = project_path / "build"
    
    console.print(f"[bold]Building project:[/bold] {project_path.name}")
    console.print(f"[dim]Configuration: {config}[/dim]")
    
    # Check for CMakeLists.txt
    if not (project_path / "CMakeLists.txt").exists():
        console.print("[red]No CMakeLists.txt found in project directory.[/red]")
        raise SystemExit(1)
    
    # Check for CMakePresets.json
    presets_file = project_path / "CMakePresets.json"
    
    # Configure if build dir doesn't exist
    if not build_dir.exists():
        console.print("[dim]Configuring CMake...[/dim]")
        configure_cmd = ["cmake", "-S", str(project_path), "-B", str(build_dir)]
        if presets_file.exists():
            configure_cmd = ["cmake", "--preset", "default", "-S", str(project_path)]
        
        result = subprocess.run(configure_cmd, capture_output=True, text=True)
        if result.returncode != 0:
            console.print(f"[red]CMake configure failed:[/red]\n{result.stderr}")
            raise SystemExit(1)
    
    # Build
    cmake_config = {"debug": "Debug", "profile": "Profile", "release": "Release"}[config]
    build_cmd = ["cmake", "--build", str(build_dir), "--config", cmake_config, "--parallel"]
    
    console.print(f"[dim]Running: {' '.join(build_cmd)}[/dim]")
    result = subprocess.run(build_cmd, capture_output=True, text=True)
    
    if result.returncode != 0:
        console.print(f"[red]Build failed:[/red]\n{result.stderr[-500:]}")
        raise SystemExit(1)
    
    console.print(f"[green]Build complete:[/green] {config}")


@project.command("run")
@click.option("--path", "-p", type=click.Path(exists=True), help="Project path")
def run(path: str | None) -> None:
    """Run an O3DE project (launches the game launcher)."""
    import subprocess
    import sys
    
    project_path = Path(path) if path else Path.cwd()
    build_dir = project_path / "build"
    
    console.print(f"[bold]Running project:[/bold] {project_path.name}")
    
    # Find the launcher executable
    project_name = project_path.name
    
    # Check common build output locations
    launcher = None
    search_patterns = [
        build_dir / "bin" / "profile" / f"{project_name}.GameLauncher.exe",
        build_dir / "bin" / "profile" / f"{project_name}.GameLauncher",
        build_dir / "bin" / "Profile" / f"{project_name}.GameLauncher.exe",
        build_dir / "bin" / "debug" / f"{project_name}.GameLauncher.exe",
    ]
    
    for p in search_patterns:
        if p.exists():
            launcher = p
            break
    
    if not launcher:
        console.print("[red]No launcher found. Build the project first with 'project build'.[/red]")
        raise SystemExit(1)
    
    console.print(f"[dim]Launching: {launcher}[/dim]")
    subprocess.Popen([str(launcher)], cwd=str(project_path))
    console.print("[green]Launched![/green]")


@project.command("add")
@click.argument("obj_type", type=click.Choice(["gem"]))
@click.argument("name")
@click.option("--path", "-p", type=click.Path(exists=True), help="Project path")
def add(obj_type: str, name: str, path: str | None) -> None:
    """Add a gem dependency to the project."""
    import json
    
    project_path = Path(path) if path else Path.cwd()
    
    console.print(f"[bold]Adding {obj_type}:[/bold] {name}")
    
    # Find project JSON
    project_json_path = None
    for candidate in ["project.2-0-0.json", "project.json"]:
        p = project_path / candidate
        if p.exists():
            project_json_path = p
            break
    
    if not project_json_path:
        console.print("[red]No project JSON found in directory.[/red]")
        raise SystemExit(1)
    
    with open(project_json_path) as f:
        data = json.load(f)
    
    # Add dependency
    # Schema 2.0.0: project.dependent.gems
    project_data = data.get("project", data)
    dependent = project_data.setdefault("dependent", {})
    gems_list = dependent.setdefault("gems", [])
    
    if name in gems_list:
        console.print(f"[yellow]Gem {name} is already a dependency.[/yellow]")
        return
    
    gems_list.append(name)
    
    with open(project_json_path, "w") as f:
        json.dump(data, f, indent=2)
    
    console.print(f"[green]Added {name} to project dependencies.[/green]")
